services:

  redis:
    image: redis:7
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"

  generador_respuestas:
    build: ./generador_respuestas
    volumes:
      - ./dataset:/app/dataset
    ports:
      - "8002:8002"

  cache_service:
    build: ./cache
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - generador_respuestas

  generador_trafico:
    build: ./generador_trafico
    depends_on:
      - cache_service

  recolector:
    build: ./metricas
    command: python recolector.py
    volumes:
      - ./output:/app/output
    depends_on:
      - redis

  analizador:
    build: ./metricas
    command: python analizador.py
    volumes:
      - ./output:/app/output
